### ISSUE TITLE
not working on mac and atom 1.6.0

### ISSUE THREAD

**Issue by deuxshaish** [atom/about#18]
I tried it on a fresh installation of atom, when I tried to paste using cmd+shift+ctrl+v on a Mac it doesn't work. with alt instead and normal pasting but nothing also.

**Comment by mnquintana** [comment]
What were you trying to paste?

**Comment by deuxshaish** [comment]
An image from the clipboard

**Comment by lee-dohm** [comment]
Atom doesn't support pasting of images, only text.

**Comment by deuxshaish** [comment]
apologies, I didn't pay attention, I clicked on a package's issue link (img-paste) and submitted
