### ISSUE TITLE
Add About to Help menu

### ISSUE THREAD

**Issue by jerone** [atom/about#2]
Most programs on Windows have a "About `<name>`" in the "Help" menu.

I used this in my `init.coffee`: 

```coffee
# Add about to the help menu
help = atom.menu.template?.filter (menu) ->
  menu.label is '&Help'
help?[0]?.submenu.push
  label: 'About Atom'
  command: 'about:about-atom'
atom.menu.update()
```

**Comment by mnquintana** [comment]
Thanks! It would be added in Atom core in https://github.com/atom/atom/pull/7377/files

**Comment by jerone** [comment]
Ah, much better if this package will be part of Atom! :+1:

**Comment by jerone** [comment]
:heart_eyes:
