### ISSUE TITLE
Restart and install button is not working

### ISSUE THREAD

**Issue by amytruong** [atom/about#21]
Was taking a look at issue https://github.com/github/atom-log/issues/340 and was having trouble with the Restart and install button on the mac side on 1.7. Ended up closing the app and reopening it and it was fine.

Tried it again via the Windows side and the app isn't closing/restarting either.
1. Click on Squirrel (or go to About)
2. Click on Restart and install
![installupdate](https://cloud.githubusercontent.com/assets/10725993/14188337/69589f6a-f723-11e5-9021-5287461df5a0.gif)

**Comment by controversial** [comment]
This still doesn't work for me. I'm on 1.7.4, trying to update to 1.8. Even after closing the About tab, quitting the app, and re-opening, the "restart and install" button does nothing.

I'm on OS X 10.11
