### ISSUE TITLE
Updating in the background does not tell the UI. showing update but then "up to date"

### ISSUE THREAD

**Issue by Stanzilla** [atom/about#24]
So https://github.com/atom/atom/releases/tag/v1.7.0-beta5 has been out for 2 days and the Squirrel icon showed up today, yet when I click it, the about page AND the update check says I'm up to date.

![atom_2016-04-10_05-27-26](https://cloud.githubusercontent.com/assets/75278/14407920/ffe3905a-fedc-11e5-8935-a8056a9014a3.png)

When I go look at the folders, I can see that beta5 is already downloaded and installed, which now makes sense out of the about page saying I'm already up to date, but it is not very transparent to the user that he has to restart Atom to actually be up to date since the UI does not communicate this at all.

![explorer_2016-04-10_05-28-31](https://cloud.githubusercontent.com/assets/75278/14407926/48285fd0-fedd-11e5-807e-9325b0561918.png)

**Comment by trainto** [comment]
It also happens to me, Windows 7, atom v1.7.2.
Squirrel icon does not disappear no matter What I do.
I haven't experienced this behaviour before I upgraded atom to 1.7.2

**Comment by Stanzilla** [comment]
@as-cii does https://github.com/atom/about/pull/27 fix this?

**Comment by as-cii** [comment]
That's very likely, thanks @Stanzilla for pointing that out. Can anyone confirm this doesn't happen anymore on 1.9.4?

**Comment by Stanzilla** [comment]
@as-cii it still happens in 1.10.beta1 so I think it will happen in 1.9.4, too

![atom_2016-08-08_06-15-09](https://cloud.githubusercontent.com/assets/75278/17469179/8858a1e0-5d2f-11e6-9dc0-ad74dc8339bd.png)

**Comment by Stanzilla** [comment]
@as-cii still does it on 1.10.beta5/6

**Comment by Stanzilla** [comment]
This still happens on 1.12.0-beta0

**Comment by Stanzilla** [comment]
@benogle this is still an issue as of 1.13.0-beta0

**Comment by technoweenie** [comment]
I saw this issue on v1.12.7, but was eventually able to resolve it.

1. Click "Get Update". It pops up window saying v1.12.7 is the latest.
2. Close and re-open Atom. The Atom menu shows it downloading an update, and eventually presents me "Restart and Install Update" button. I click it.
3. The Atom menu shows 1.127 again, but also shows it downloading an update, and eventually presents me "Restart and Install Update" button. I hold my breath and click it.
4. Now I'm on v1.13.0 :metal:

(I do have `Automatically download updates` enabled in the About screen)

**Comment by lee-dohm** [comment]
I believe that this has been fixed in the intervening time. If anyone runs into this again, please open a new issue and provide all of the required information.

Thanks for all your help :+1:
