### ISSUE TITLE
Can't click blue Squirrel anymore

### ISSUE THREAD

**Issue by amytruong** [atom/about#28]
Not sure if this is a :bug: or a change @as-cii but I can't click the blue Squirrel anymore to view release notes. It just keeps getting away from me when I try. 😬 
![about](https://cloud.githubusercontent.com/assets/10725993/14751728/137c073a-0867-11e6-9501-9e674d7b6b47.gif)

**Comment by as-cii** [comment]
I _think_ the tooltip is not supposed to be clickable. Users should just be able to click the squirrel icon, which in turn should open the about page, and from there you can check the release notes.

So, if the latter is happening I would say this is not a regression. 👍

**Comment by lee-dohm** [comment]
If the tooltip isn't intended to be clickable, the text should be changed to suggest clicking the squirrel :grinning:
