### ISSUE TITLE
 Gathering syntax when opening files with a large "set" code

### ISSUE THREAD

**Issue by KennyDalglish** [atom/about#34]
I do not know where would be the best to write about it, so I will write here.
When you open a file of 30,000 lines of code - syntax highlighting flies. What is it? I use Atom for Pawn language

**Comment by 50Wliu** [comment]
[We're trying to control the amount of Issues that we have to triage and track](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For general questions, [the Atom message board](https://discuss.atom.io) is where you'll probably be able to find answers faster.
