### ISSUE TITLE
"check for updates" button for Linux

### ISSUE THREAD

**Issue by pedzed** [atom/about#38]
On Windows and macOS you have a button to update Atom to the latest version. It would be nice if Linux also had that. If the update functionality will not be implemented (anytime soon), it would be nice if there's a button that tells you if an update is available - just so you know that your version is outdated. And perhaps also instructions on how to update.

Currently, you have to check at https://github.com/atom/atom/releases to see if there is a newer version. Understandably, that is far from ideal.

**Comment by doxman** [comment]
Added a link to updating instructions for now. I would also like to add a "Check for updates" function but am uncertain how to proceed -- left some more thoughts on this in the PR's "Alternate Designs" section.

(first attempt at contributing to open source, please be gentle :slightly_smiling_face: )

**Comment by daviwil** [comment]
This issue was moved to atom/atom#17915
