### ISSUE TITLE
Update squirrel stays even though running latest version

### ISSUE THREAD

**Issue by Coysh** [atom/about#50]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The bottom-right 'squirrel' continues to show even when on the latest version.
"An update will be installed the next time Atom is relaunched" - I have relaunched

### Steps to Reproduce

1. Install Atom stable that is not the latest Atom version, `1.14.0` was used in these steps 
2. Wait for Atom to automatically update so the squirrel appears in the `status-bar`
3. Manually install the latest Atom beta (`1.15.0-beta1`) without restarting to install the `1.14.1` update

**Expected behavior:** No update squirrel in the `status-bar` because latest beta is the latest version

**Actual behavior:** Update squirrel is in the `status-bar` asking to restart and install a new version.

**Reproduces how often:** 100%

![image](https://cloud.githubusercontent.com/assets/1058982/22818661/a6a83620-ef6e-11e6-824c-ccdcd738c898.png)

----

Versions

OS: Windows 7

atom --version
Atom : 1.14.0-beta1
Electron: 1.3.13
Chrome : 52.0.2743.82
Node : 6.5.0

apm --version
apm 1.15.1
npm 3.10.5
node 4.4.5 ia32
python
git 2.8.2.windows.1
visual studio 2010

**Comment by dev169** [comment]
@Coysh I had the same issue (https://github.com/atom/atom/issues/13633). Fixed for me in 1.14.0-beta2, did you try updating?

**Comment by Coysh** [comment]
@dev169 yes. 1.14.0-beta2 fixes this for me, but I had to manually update.

**Comment by Ben3eeE** [comment]
Reopening because this is still an issue. I have updated the body of the issue with steps to reproduce.

**Comment by damieng** [comment]
I suspect this is a side-effect of the wanting-to-downgrade problem (it was last time) and it will disappear once the next detected-update goes out.

**Comment by demetris** [comment]
The squirrel disappeared for me as soon as I updated from 1.15.0-beta2 x64 to 1.15.0-beta3 x64.

`localStorage.getItem('about:version-available')` now returns `null`, rather than a version from the stable channel.

OS: Windows 8.1 64-bit

**Comment by marnen** [comment]
This is happening for me on 1.21.1 on MacOS 10.12.6 (Sierra). The interesting part is that `localStorage.getItem('about:version-available')` returns `1.21.0`, which would be a downgrade...

**Comment by marnen** [comment]
...so I used the dev tools to clear local storage, which seems to have fixed it.

**Comment by tofu-rocketry** [comment]
Same here. Running 1.26.1 on Windows 7, `localStorage.getItem('about:version-available')` returns` 1.26.0`.
