### ISSUE TITLE
Portable mode not possible to automatically download update, so better info in about

### ISSUE THREAD

**Issue by Koshmaar** [atom/about#51]
### Description

I downloaded Atom as zip file on Windows 7 x64, because I prefer to put tools like that in one place. But in this case the auto update doesn't work, I'm still at 1.12.3 and clicking button "Check now" shows "No update available"

It's not possible to do auto update in standalone mode - so in the About page it shouldn't say "Atom is up to date", there shouldn't be button check now, or checkbox "Automatically download updates". 

Instead we should see link to atom releases pages, with info on how to manually update Atom.

### Versions

1.12.3  portable install
Windows 7 x64

### Additional Information

First reported https://discuss.atom.io/t/broken-auto-update-in-standalone-mode/38965/2

**Comment by lee-dohm** [comment]
Thanks for the feedback!

This could definitely be improved. Since the maintainer team isn't going to be taking this on any time soon, I'm going to close it. But I've marked it `help-wanted` to let people know that we would accept a well-written pull request for the feature.

Thanks again :+1:
