### ISSUE TITLE
atom-text-editor.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by hebbet** [atom/about#55]
The contents of `atom-text-editor` elements are no longer encapsulated
within a shadow DOM boundary. Please, stop using `shadowRoot` and access
the editor contents directly instead.
```
atom-text-editor.Object.defineProperty.get (C:\Users\pascal\AppData\Local\atom\app-1.17.0-beta0\resources\app\src\text-editor-element.js:68:18)
<unknown> (C:\Users\pascal\.atom\packages\css-color-underline\lib\main.coffee:14:29)
Function.module.exports.Emitter.simpleDispatch (<embedded>:62256:20)
Emitter.emit (<embedded>:62372:34)
<unknown> (<embedded>:2784:38)
Function.module.exports.Emitter.simpleDispatch (<embedded>:62256:20)
```

**Comment by damieng** [comment]
Based on the stack trace this would appear to be a problem with css-color-underline package not Atom's about package..  

I believe https://github.com/elinaldosoft/css-color-underline is their repo.
