### ISSUE TITLE
ProviderManager.registerProvider is deprecated.

### ISSUE THREAD

**Issue by bbroens** [atom/about#60]
Autocomplete provider 'Object(mavensmate-apexprovider)'
contains an `id` property.
An `id` attribute on your provider is no longer necessary.
See https://github.com/atom/autocomplete-plus/wiki/Provider-API
```
ProviderManager.registerProvider (<embedded>:85895:22)
requireAutocompleteManagerAsync (<embedded>:8477:69)
Immediate.setImmediate (<embedded>:8404:17)
runCallback (timers.js:574:20)
tryOnImmediate (timers.js:554:5)
process._immediateCallback (timers.js:533:5)
```

**Comment by thomasjo** [comment]
Thanks for contributing!

It appears that this is being caused by the [mavensmate-atom](https://atom.io/packages/mavensmate-atom) package, not Atom itself. You should file this issue on [their repository](https://github.com/joeferraro/MavensMate-Atom) so they can fix the problem.
