### ISSUE TITLE
AutocompleteManager.deprecateForSuggestion is deprecated.

### ISSUE THREAD

**Issue by ddyllen-z** [atom/about#62]
Autocomplete provider 'ClassProvider(undefined)'
returns suggestions with a `prefix` attribute.
The `prefix` attribute is now `replacementPrefix` and is optional.
See https://github.com/atom/autocomplete-plus/wiki/Provider-API
```
AutocompleteManager.deprecateForSuggestion (<embedded>:40436:20)
<unknown> (<embedded>:40293:44)
```

**Comment by 50Wliu** [comment]
This is an issue with one of your autocomplete packages.
