### ISSUE TITLE
HTMLElement.shadowRoot is deprecated.

### ISSUE THREAD

**Issue by maz0401** [atom/about#64]
The contents of `atom-text-editor` elements are no longer encapsulated
within a shadow DOM boundary. Please, stop using `shadowRoot` and access
the editor contents directly instead.
```
HTMLElement.shadowRoot (D:\Program Files\atom-x64-windows\Atom Beta x64\resources\app\src\text-editor-element.js:13:10)
MarkdownScrlSync.getVisTopHgtBot (C:\Users\vshzh\.atom\packages\markdown-scroll-sync\lib\utils.coffee:20:33)
MarkdownScrlSync.setMap (C:\Users\vshzh\.atom\packages\markdown-scroll-sync\lib\map.coffee:25:14)
MarkdownScrlSync.startTracking (C:\Users\vshzh\.atom\packages\markdown-scroll-sync\lib\main.coffee:75:12)
<unknown> (C:\Users\vshzh\.atom\packages\markdown-scroll-sync\lib\main.coffee:58:23)
Workspace.observeActivePaneItem (<embedded>:26308:13)
```

**Comment by damieng** [comment]
Hi.

The stack trace indicates this is a problem with the [markdown-scroll-sync](https://atom.io/packages/markdown-scroll-sync) package. As this is a third party package we can not address it but you should check and potentially raise an issue with the authors of that package.
