### ISSUE TITLE
<unknown> is deprecated.

### ISSUE THREAD

**Issue by nudelx** [atom/about#70]
You have the core package "about" installed as a community package. See https://github.com/atom/dalek for how this causes problems and instructions on how to correct the situation.
```
<unknown> (/Users/nudelx/.atom/packages/dalek/lib/main.js:14:14)
Generator.next (null:null:null)
step (/Users/nudelx/.atom/packages/dalek/lib/main.js:1:428)
process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by lee-dohm** [comment]
Yes, the above message is for you @nudelx. Please read the README at https://github.com/atom/dalek for information and instructions :grinning:
