### ISSUE TITLE
Broken Atom logo

### ISSUE THREAD

**Issue by simurai** [atom/about#78]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The Atom logo looks broken. 

### Steps to Reproduce

1. Make sure you're on latest master
2. Open About pane

**Expected behavior:** [What you expect to happen]

Logo to look ok

**Actual behavior:** [What actually happens]

Logo looks broken. There is a line missing:

![image](https://user-images.githubusercontent.com/378023/39732176-cf237708-52a6-11e8-9a92-63196998efde.png)

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

```
Atom    : 1.28.0-dev-a3631f0da
Electron: 1.7.14
Chrome  : 58.0.3029.110
Node    : 7.9.0
```

```
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.28.0-dev-a3631f0da
python 2.7.10
git 2.12.2
```

**Comment by 50Wliu** [comment]
This is my fault - didn't inspect my changes closely enough.
