### ISSUE TITLE
"No README" showing up in Atom

### ISSUE THREAD

**Issue by jaller94** [atom/about#85]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

![The settings page of the about package says No README](https://user-images.githubusercontent.com/10872136/43625720-5856ef06-96a3-11e8-96ee-d97b17177b21.png)

### Steps to Reproduce

1. Go into the packages settings
2. Search and select the about package

**Expected behavior:** The Readme shows a description of the package’s use. Most likely the text would be the same text as this repository’s README.md.

**Actual behavior:** It says "No README"

**Reproduces how often:** every time

### Versions

Atom 1.28.0 on Linux_x64
Atom 1.29.0 on MacOS

**Comment by rsese** [comment]
This issue was moved to atom/settings-view#1069
